
services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo_db:/data/db

  app:
    image: ripweb/my-bot:latest
    build: .
    restart: always
    environment:
      TOKEN: 5590613650:AAGDWeQHSf4ZPhKaHGcsrB5tLA0vTjfVNT8
      URI: mongodb://mongo_db:27017/my-bot
      USERNAME: my2232bot
      ADMINS: "7371046616"
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
