services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  app:
    image: ripweb/my-bot:latest
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo_db

volumes:
  mongo_db:
    name: "mongo_db"